openapi: 3.0.0
info:
  version: 1.0.0
  title: Commitments API
  description: The API for taiyi preconfimation service
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/luban-0d2/taiyi/1.0.0
  - description: Holesky
    url: ' https://taiyi.holesky.luban.wtf'
    
paths:
  /commitments/v0/slots:
    get:
      operationId: getSlots
      tags:
        - v1
      summary: Get a list of slots which are available in the current and next epoch
      description: |
        * Used by users to know when to submit preconf requests for an upcoming slot.
        * Returns an array of SlotInfo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SlotInfo'
                  
  /commitments/v0/preconf_fee:
    post:
      operationId: getFee
      tags:
        - v1
      summary: Returns a fee quoted in "wei" per gas
      description: |
        * Used to fetch fee
      requestBody:
        description: Reserve blockspace request
        required: true
        content:
          application/json:
            schema:
              type: integer
              format: uint64
              example: 53920
      responses:
        '200': 
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreconfFeeResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                 properties:
                  code:
                    description: Either specific error code in case of invalid request or http status code
                    type: number
                  message:
                    description: Message describing error
                    type: string
              example:
                code: 500
                message: internal server error
                
  /commitments/v0/reserve_blockspace:
    post:
      operationId: reserveBlockspace
      tags:
        - v1
      summary: Reserves blockspace for a slot
      description: |
        * Used to reserve blockspace for a slot for later use.
        * One must have reserved some blockspace before submiting a preconf transaction
      parameters:
        - schema:
            type: string
            format: hex
            pattern: '^0x[a-fA-F0-9]{130}$'
            example: '0x8a726dc1d89dc0b10a27130c562cce2d346f2bbac1af683d9b55632825e4abc0480bcf25276452a3c076f2a5d756c6deedd552cfc343dd34a5953835f4d7c8a71c'
          in: header
          name: x-taiyi-signature
          description: An ECDSA signature from the user over fields of request body
          required: true
      requestBody:
        description: Reserve blockspace request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReserveBlockSpaceRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReserveBlockSpaceResponse'
        '400':
          description: Error
          content:
            application/json:
              schema:
                required: 
                  - code
                  - message
                properties:
                  code:
                    description: Either specific error code in case of invalid request or http status code
                    type: number
                    example: 400
                  message:
                    description: Message describing error
                    type: string
                    example: requested blockspace not available for slot
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                 properties:
                  code:
                    description: Either specific error code in case of invalid request or http status code
                    type: number
                  message:
                    description: Message describing error
                    type: string
              example:
                code: 500
                message: internal server error
                    
                
  /commitments/v0/submit_transaction:
    post:
      operationId: submitTransaction
      tags:
        - v1
      summary: Used to submit transaction
      description: |
        * Returns a commitment from the gateway
      parameters:
        - schema:
            type: string
          in: header
          name: x-taiyi-signature
          required: true
          description: An ECDSA signature from the user over fields of body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitTransactionRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: hex
                pattern: '^0x[a-fA-F0-9]{130}$'
                description: An ECDSA signature signed by the gateway over the request body.
                example: '0x8a726dc1d89dc0b10a27130c562cce2d346f2bbac1af683d9b55632825e4abc0480bcf25276452a3c076f2a5d756c6deedd552cfc343dd34a5953835f4d7c8a71c'
        '400':
          description: Error
          content:
            application/json:
              schema:
                required: 
                  - code
                  - message
                properties:
                  code:
                    description: Either specific error code in case of invalid request or http status code
                    type: number
                    example: 400
                  message:
                    description: Message describing error
                    type: string
                    example: Transaction for this request id was already submitted
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                 properties:
                  code:
                    description: Either specific error code in case of invalid request or http status code
                    type: number
                  message:
                    description: Message describing error
                    type: string
              example:
                code: 500
                message: internal server error
components:
  schemas:
    SubmitTransactionRequest:
      type: object
      required:
        - request_id
        - transaction
      properties:
        request_id:
          type: string
          format: uuid
          example: 0729a580-2240-11e6-9eb5-0002a5d5c51b
        transaction:
          type: string
          x-go-type: geth_core_types.Transaction
          x-go-type-import:
            path: github.com/ethereum/go-ethereum/core/types
            name: geth_core_types
    ReserveBlockSpaceRequest:
      type: object
      required: 
        - target_slot
        - deposit
        - tip
        - gas_limit
        - blob_count
      properties:
        target_slot:
          type: integer
          format: uint64
          example: '64'
        gas_limit:
          type: integer
          format: uint64
          example: '983798'
        deposit:
          type: integer
          format: uint256
          x-go-type: geth_hexutil.U256
          x-go-type-import:
            path: github.com/ethereum/go-ethereum/common/hexutil
            name: geth_hexutil
          description: |
            This is the amount deducted from the user's escrow balance when the user fails to submit a transaction for the allocated blockspace.
            
            The deposit is calculated as follows:
            { gas_limit * gas_fee + blob_count * blob_gas_fee } * 0.5
          example: '293872836'
        tip:
          type: integer
          format: uint256
          x-go-type: geth_hexutil.U256
          x-go-type-import:
            path: github.com/ethereum/go-ethereum/common/hexutil
            name: geth_hexutil
          description: |
            This is the amount deducted from the user's escrow balance along with `[deposit]` when the user submits a transaction for the allocated blockspace.
            
            The tip is calculated as follows:
            { gas_limit * gas_fee + blob_count * blob_gas_fee } * 0.5
          example: '293872836'
        blob_count:
          type: integer
          format: uint32
          example: '1'
          minimum: 0
          maximum: 6
    ReserveBlockSpaceResponse:
      type: object
      required: 
        - request_id
        - signature
      properties:
        request_id:
          type: string
          format: uuid
          example: 0729a580-2240-11e6-9eb5-0002a5d5c51b
        signature:
          type: string
          format: hex
          pattern: '^0x[a-fA-F0-9]{130}$'
          description: An ECDSA signature signed over request body and request id by the gateway
          example: '0x8a726dc1d89dc0b10a27130c562cce2d346f2bbac1af683d9b55632825e4abc0480bcf25276452a3c076f2a5d756c6deedd552cfc343dd34a5953835f4d7c8a71c'
    SlotInfo:
      type: object
      required: [slot, gas_available, blobs_available, constraints_availaible]
      properties:
        slot:
          type: integer
          format: uint64
          example: '64'
        gas_available:
          type: integer
          format: uint64
          example: '983798'
        blobs_available:
          type: integer
          format: uint32
          example: '3'
          minimum: 0
          maximum: 6
        constraints_available:
          type: integer
          format: uint32
          example: '78'
          minimum: 0
          maximum: 256
    PreconfFeeResponse:
      type: object
      required: [gas_fee, blob_gas_fee]
      description: denominated in wei
      properties:
        gas_fee:
          type: integer
          format: uint64
          example: 682000000
        blob_gas_fee:
          type: integer
          format: uint64
          example: 408014488
